apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "searchruler.fullname" . }}-manager
  labels:
    {{- include "searchruler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - searchrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - searchrules/finalizers
  verbs:
  - update
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - searchrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - ruleractions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - ruleractions/finalizers
  verbs:
  - update
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - ruleractions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - queryconnectors
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - queryconnectors/finalizers
  verbs:
  - update
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - queryconnectors/status
  verbs:
  - get
  - patch
  - update