apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rabbitstalker.fullname" . }}-manager
  labels:
    {{- include "rabbitstalker.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - daemonsets
      - deployments
      - secrets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rabbit-stalker.prosimcorp.com
    resources:
      - workloadactions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rabbit-stalker.prosimcorp.com
    resources:
      - workloadactions/finalizers
    verbs:
      - update
  - apiGroups:
      - rabbit-stalker.prosimcorp.com
    resources:
      - workloadactions/status
    verbs:
      - get
      - patch
      - update
