apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "reforma.fullname" . }}-manager
  labels:
    {{- include "reforma.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - reforma.prosimcorp.com
    resources:
    - patches
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - reforma.prosimcorp.com
    resources:
    - patches/finalizers
    verbs:
    - update
  - apiGroups:
    - reforma.prosimcorp.com
    resources:
    - patches/status
    verbs:
    - get
    - patch
    - update

  - apiGroups:
      - reforma.prosimcorp.com
    resources:
      - prepatches
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - reforma.prosimcorp.com
    resources:
      - prepatches/finalizers
    verbs:
      - update
  - apiGroups:
      - reforma.prosimcorp.com
    resources:
      - prepatches/status
    verbs:
      - get
      - patch
      - update
