{{- if and (.Values.controller.metrics.enabled) (.Values.controller.metrics.rbacProtectionEnabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "reforma.fullname" . }}-metrics-reader-role
  labels:
    {{- include "reforma.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{- end }}