# Default values for Reforma.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Following custom ClusterRole is a place where to add the type of resources
# allowed to be replicated by Replika. By default, only Secrets and ConfigMaps are allowed,
# but it's possible to add extra resources or even get rid of some of them for improved security
customClusterRole:
  # Specifies whether a custom clusterRole should be created
  create: true

  # Annotations to add to the clusterRole
  annotations: {}

  # A set of rules as documented here : https://kubernetes.io/docs/reference/access-authn-authz/rbac/
  rules:
  - apiGroups: ['']
    resources:
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  clusterRoleBinding:
    # Annotations to add to the clusterRoleBinding
    annotations: {}

# TODO
controller:

  replicaCount: 1

  image:
    repository: prosimcorp/reforma
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "reforma-controller-manager"

  podAnnotations: {}

  podSecurityContext: {}

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  metrics:
    # Specify whether metrics should be exposed or not
    enabled: false

    # Specify whether metrics should be protected by RBAC proxy
    rbacProtectionEnabled: false

    # Specifies configuration for a Service resource to expose the metrics
    service:
      enabled: false
      type: ClusterIP
      port: 9090
